-- 9 14/03/2023

use dbms_lab;

-- 1
SELECT D.DEPTNO FROM DEPT D WHERE DEPTNO NOT IN (SELECT DISTINCT DEPTNO FROM EMP);

-- 2
SELECT DEPTNO, JOB, COUNT(*) AS NUM_EMPLOYEES, AVG(SAL) AS AVG_SALARY FROM EMP GROUP BY DEPTNO, JOB;

-- 3
SELECT JOB, MAX(AVG_SAL) AS MAX_AVG_SALARY FROM (SELECT JOB, AVG(SAL) AS AVG_SAL FROM EMP WHERE JOB != 'President' GROUP BY JOB, DEPTNO) AS JOB_AVG_SALARY GROUP BY JOB;

-- 4
SELECT * FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(*) >= 2);

-- 5
SELECT DEPTNO, COUNT(*) AS NUM_EMPLOYEES FROM EMP GROUP BY DEPTNO HAVING COUNT(*) > 3;

-- 6
SELECT D.DEPTNO, E.ENAME, E.SAL FROM EMP E INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO WHERE (E.DEPTNO, E.SAL) IN (SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO) ORDER BY DEPTNO;

-- 7
SELECT DEPTNO, AVG(SAL) AS AVG_SALARY FROM EMP GROUP BY DEPTNO HAVING AVG(SAL) < (SELECT AVG(SAL) FROM EMP);

