-- EX 10 21/03/2023
USE DBMS_LAB;

-- 1
SELECT E1.* FROM EMP E1 JOIN EMP E2 ON E1.SAL > E2.SAL AND E2.ENAME = "BLAKE";

-- 2
SELECT E1.* FROM EMP E1 JOIN EMP E2 ON E1.JOB = E2.JOB AND E2.ENAME = "ALLEN";

-- 3
SELECT e.* FROM EMP e JOIN (SELECT SAL FROM EMP WHERE ENAME IN ('FORD', 'SMITH')) s ON e.SAL = s.SAL ORDER BY e.ENAME DESC;

-- 4
SELECT E1.EMPNO, E1.ENAME, E1.JOB, E1.MGR, E1.HIREDATE, E1.SAL, E1.COMM, E1.DEPTNO FROM EMP E1 JOIN EMP E2 ON (E1.JOB =E2.JOB AND E2.ENAME = "MILLER") OR (E1.SAL > E2.SAL AND E2.ENAME = "ALLEN");

-- 5
SELECT e.* FROM EMP e INNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO WHERE d.DNAME = 'SALES' ORDER BY e.SAL DESC LIMIT 1;

-- 6 
SELECT E1.* FROM EMP E1 JOIN (SELECT JOB, MAX(HIREDATE) AS MAX_HIREDATE FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'KING') GROUP BY JOB) E2 ON E1.JOB = E2.JOB AND E1.HIREDATE < E2.MAX_HIREDATE;

 

-- 7
SELECT DNAME, ENAME, SAL FROM EMP E1 JOIN DEPT D1 ON E1.DEPTNO = D1.DEPTNO WHERE SAL = (SELECT MAX(SAL) FROM EMP E2 WHERE E1.DEPTNO = E2.DEPTNO);


-- 8
SELECT * FROM EMP WHERE SAL = (SELECT (MAX(SAL) + MIN(SAL))/2 FROM EMP);
SELECT e.* FROM EMP e JOIN (SELECT AVG(SAL) AS AVG_SAL FROM (SELECT MAX(SAL) AS SAL FROM EMP UNION SELECT MIN(SAL) AS SAL FROM EMP) s) a ON e.SAL = a.AVG_SAL;

-- 9
SELECT * FROM EMP E1 JOIN EMP E2 ON E1.HIREDATE = E2.HIREDATE AND E1.EMPNO <> E2.EMPNO ORDER BY E1.HIREDATE;

SELECT E1.EMPNO, E1.ENAME, E1.JOB, E1.MGR, E1.HIREDATE, E1.SAL, E1.COMM, E1.DEPTNO FROM EMP E1 JOIN EMP E2 ON E1.HIREDATE = E2.HIREDATE AND E1.EMPNO <> E2.EMPNO ORDER BY E1.HIREDATE;

-- 10
SELECT E1.EMPNO, E1.ENAME, E1.JOB, E1.MGR, E1.HIREDATE, E1.SAL, E1.COMM, E1.DEPTNO FROM EMP E1 JOIN EMP E2 ON E1.MGR = E2.EMPNO AND E1.HIREDATE < E2.HIREDATE ORDER BY E1.HIREDATE;

